#!/usr/bin/env bash
# A script that configures HAproxy on lb-01 server.
apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

cp -a /etc/haproxy/haproxy.cfg{,.orig}
# Configure HAproxy
cat << EOF > /etc/haproxy/haproxy.cfg
global
  log 127.0.0.1 local0
  log 127.0.0.1 local1 notice
  chroot /var/lib/haproxy
  pidfile /var/run/haproxy.pid
  maxconn 4096

defaults
  log global
  mode http
  option httplog
  option dontlognull
  timeout connect 5000ms
  timeout client 50000ms
  timeout server 50000ms

frontend http
  bind *:80
  default_backend webservers

backend webservers
  balance roundrobin
  server 389728-web-01 107.23.95.21:80 check
  server 389728-web-02 34.204.81.3:80 check
EOF

# Make HAproxy start on boot
sudo systemctl enable haproxy

# Start HAproxy
sudo systemctl start haproxy

