#!/usr/bin/env bash
# Run Nginx as Nginx
sed -i -e 's/#user www-data/user nginx/' -e '/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
